import type { CredibilityItem } from '../types';

export const credibilityItems: CredibilityItem[] = [
  {
    id: 'press-vpro-sub-makers',
    label: 'Maak kennis met de zes SUB-makers',
    kind: 'press',
    project: 'gen-c',
    logo: '/logos/vpro.svg',
    url: 'https://www.vpro.nl/vpro-dorst/artikelen/maak-kennis-met-de-zes-sub-makers',
    note: 'Gen C',
  },
  {
    id: 'press-vpro-sub-release',
    label: 'SUB: zes jonge makers onderzoeken vertical, Gen Z en subculturen',
    kind: 'press',
    project: 'gen-c',
    logo: '/logos/vpro.svg',
    url: 'https://www.vpro.nl/vpro-dorst/artikelen/sub-zes-jonge-makers-onderzoeken-vertical-gen-z-en-subculturen',
    note: 'Gen C',
  },
  {
    id: 'press-broadcast-sub',
    label: 'Broadcast Magazine coverage of SUB',
    kind: 'press',
    project: 'gen-c',
    logo: '/logos/broadcast-magazine.svg',
    url: 'https://www.broadcastmagazine.nl/bmy/sub-zes-jonge-makers-onderzoeken-vertical-gen-z-en-subculturen/',
    note: 'Gen C',
  },
  {
    id: 'press-wintertuin-cinepoems',
    label: 'Cinepoems production page',
    kind: 'press',
    project: '7-plus-1',
    logo: '/logos/wintertuin.svg',
    coLogos: ['/logos/inscience.svg'],
    url: 'https://wintertuin.nl/productie/cinepoems/',
    note: '7+1',
  },
  {
    id: 'press-nieuwe-gronden-2024',
    label: 'Nieuwe Gronden 2024 programme page',
    kind: 'press',
    project: '7-plus-1',
    logo: '/logos/wintertuin.svg',
    coLogos: ['/logos/inscience.svg'],
    url: 'https://wintertuin.nl/productie/nieuw-gronden/',
    note: '7+1',
  },
  {
    id: 'press-npf-2024',
    label: 'Nederlands Poëziefilm Festival 2024 programmaboekje',
    kind: 'festival',
    project: '7-plus-1',
    logo: '/logos/npf.svg',
    url: 'https://poeziefilmfestival.nl/wp-content/uploads/NPF-programmaboekje24-10.pdf',
    note: '7+1',
  },
  {
    id: 'press-fabrica-co-ecologies',
    label: 'Fabrica Co-ecologies residency announcement',
    kind: 'press',
    project: 'general',
    logo: '/logos/fabrica.svg',
    url: 'https://www.fabrica.it/en/co-ecologies-beyond-the-anthropocene/',
  },
  {
    id: 'press-fabrica-blooming',
    label: 'Fabrica Blooming in Embers programme',
    kind: 'press',
    project: 'general',
    logo: '/logos/fabrica.svg',
    url: 'https://www.fabrica.it/en/blooming-in-embers/',
  },
];
